// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// import "github.com/a-h/templ"
func ReservationHead() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script src=\"https://cdn.jsdelivr.net/npm/fullcalendar@6.1.19/index.global.min.js\"></script><script>\n window.currentCourtId = 1; // default\n\n    function resetCalendar(id) {\n        console.log(\"reset kalendare\")\n\n        const el = document.getElementById('calendar');\n        console.log(\"a\" + el.dataset.initialized)\n        if (el && el.dataset.initialized) {\n            el.dataset.initialized = \"\";\n        }\n        console.log(\"b\" + el.dataset.initialized)\n        window.currentCourtId = id\n        initCalendar()\n    }\n\n   function initCalendar() {\n     const el = document.getElementById('calendar');\n     if (!el || el.dataset.initialized) return; // už inicializovaný nebo není na stránce\n     const calendar = new FullCalendar.Calendar(el, {\n       initialView: 'timeGridWeek',\n       locale: 'cs',\n       timeZone: 'Europe/Prague',\n       slotMinTime: '08:00:00',\n       slotMaxTime: '22:00:00',\n       slotDuration: '01:00:00',\n       selectable: true,\n       events: {\n         url: '/api/events',\n         extraParams: () => ({ court_id: window.currentCourtId })\n       },\n       select: function (info) {\n         console.log('Vybral jsi slot:', info.startStr, info.endStr);\n         // tady můžeš spustit htmx GET na formulář\n       }\n     });\n\n     calendar.render();\n     el.dataset.initialized = \"true\"; // označ element, aby se znovu nespustil\n   }\n\n   // inicializace při prvním načtení\n   document.addEventListener('DOMContentLoaded', initCalendar);\n\n   // inicializace při každém HTMX swapu do #centre-page\n   document.body.addEventListener('htmx:afterSwap', function (evt) {\n     if (evt.target.id === \"centre-page\") {\n       initCalendar();\n     }\n   });\n </script><link rel=\"stylesheet\" href=\"css/reservation.css\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Areal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"areal\"><img src=\"/images/areal.png\" alt=\"Sportoviště\" class=\"areal_img\"><div class=\"areal_overlay\"><!-- ZÓNA 1: obdélník --><button class=\"zone zone--rect hriste-1\" aria-label=\"Hřiště 1\" hx-on:click=\"resetCalendar(1); document.getElementById('field-name').innerText='Hřiště 1'\">Hřiště 1</button><!--      hx-on:click=\"document.getElementById('field-name').innerText='Hřiště 1'; initCalendar()\"--><button class=\"zone zone--rect hriste-2\" aria-label=\"Hřiště 2\" hx-on:click=\"resetCalendar(2); document.getElementById('field-name').innerText='Hřiště 2'\">Hřiště 2</button><!--          hx-on:click=\"window.currentCourtId=2; el.dataset.initialized=false; initCalendar(); document.getElementById('field-name').innerText='Hřiště 2'\"--><button class=\"zone zone--poly hriste-3\" aria-label=\"Hřiště 3\" hx-on:click=\"resetCalendar(3); document.getElementById('field-name').innerText='Hřiště 3'\">Hřiště 3</button></div></div><!-- todo tady by se dalo na hoover vykresilt info o hristich --><div id=\"detail\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Form() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		return nil
	})
}

func Reservation() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Areal().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div><h1 id=\"field-name\">Calendar</h1></div><div id=\"form-div\"></div><div id=\"calendar\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
