// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CancelReservationSuccess() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw("<!DOCTYPE html>").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html lang=\"cs\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\"><title>Zrušení rezervace — TJ Slavoj Loštice</title><link href=\"/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"><link rel=\"stylesheet\" href=\"/assets/css/templatemo-finance-business.css\"><link rel=\"icon\" type=\"image/svg+xml\" href=\"/images/favicon.svg\"></head><body><div class=\"page-heading header-text\"><div class=\"container\"><div class=\"row\"><div class=\"col-md-12\"><h1>Zrušení rezervace</h1></div></div></div></div><div class=\"container py-5\"><div class=\"row justify-content-center\"><div class=\"col-md-6 text-center\"><div class=\"bg-light p-5 rounded\"><span style=\"font-size:3rem; color:#28a745;\">&#10003;</span><h3 class=\"mt-3\">Rezervace byla zrušena</h3><p class=\"text-muted mt-2\">Vaše rezervace byla úspěšně zrušena.</p><a href=\"/\" class=\"filled-button mt-3 d-inline-block\">Zpět na hlavní stránku</a></div></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func CancelReservationError() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw("<!DOCTYPE html>").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<html lang=\"cs\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\"><title>Zrušení rezervace — TJ Slavoj Loštice</title><link href=\"/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"><link rel=\"stylesheet\" href=\"/assets/css/templatemo-finance-business.css\"><link rel=\"icon\" type=\"image/svg+xml\" href=\"/images/favicon.svg\"></head><body><div class=\"page-heading header-text\"><div class=\"container\"><div class=\"row\"><div class=\"col-md-12\"><h1>Zrušení rezervace</h1></div></div></div></div><div class=\"container py-5\"><div class=\"row justify-content-center\"><div class=\"col-md-6 text-center\"><div class=\"bg-light p-5 rounded\"><span style=\"font-size:3rem; color:#ec543d;\">&#10007;</span><h3 class=\"mt-3\">Rezervaci se nepodařilo zrušit</h3><p class=\"text-muted mt-2\">Zkuste to prosím znovu později, nebo kontaktujte administrátora na <a href=\"mailto:info@slavojlostice.cz\" style=\"color:#ec543d;\">info@slavojlostice.cz</a>.</p><a href=\"/\" class=\"filled-button mt-3 d-inline-block\">Zpět na hlavní stránku</a></div></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
