// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Documents() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"page-heading header-text\"><div class=\"container\"><div class=\"row\"><div class=\"col-md-12\"><h1>Dokumenty</h1><span>Ke stažení a prohlížení</span></div></div></div></div><div class=\"contact-information\"><div class=\"container\"><div class=\"row\"><div class=\"col-md-12\"><div class=\"section-heading\"><h2>Dostupné <em>dokumenty</em></h2></div></div></div><div class=\"row\" style=\"margin-bottom: 30px;\"><div class=\"col-md-12\" style=\"display:flex; gap:12px; flex-wrap:wrap; justify-content:center;\"><button class=\"filled-button\" style=\"width:200px;\" onclick=\"showDoc('/docs/test.pdf')\">Stanovy klubu</button> <button class=\"filled-button\" style=\"width:200px;\" onclick=\"showDoc('/docs/test.pdf')\">Provozní řád</button> <button class=\"filled-button\" style=\"width:200px;\" onclick=\"showDoc('/docs/test.pdf')\">Ceník</button></div></div></div></div><div style=\"display:flex; justify-content:center; padding: 0 10% 40px;\"><iframe id=\"doc-viewer\" src=\"\" style=\"width:100%;height:90vh;border:0;display:none;border-radius:5px;box-shadow:0 2px 16px rgba(0,0,0,0.12);\"></iframe></div><script>\n    function showDoc(src) {\n        var frame = document.getElementById('doc-viewer');\n        frame.src = src;\n        frame.style.display = 'block';\n    }\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
